#!/bin/bash
#
# Geodineum CLI — Register Command
# ==================================
# Single registration authority for the entire ecosystem.
# Creates .geodineum/ in the service root, wraps onboard-service.sh
# (ACL + streams + registry), and generates gnode_services.yaml for
# daemon capability discovery.
#
# This is the ONLY registration path. Theme-side registration is removed.
# See the registration-flow architecture documentation for rationale.
#
# Requires: common.sh sourced first
#

# =============================================================================
# YAML Format Detection & Conversion
# =============================================================================

# Detect if a YAML file is in flat format (wp-config) or daemon format (gnode_services)
detect_yaml_format() {
    local file="$1"
    if grep -q "^services:" "$file" 2>/dev/null; then
        echo "daemon"
    elif grep -q "^capabilities:" "$file" 2>/dev/null; then
        echo "flat"
    else
        echo "unknown"
    fi
}

# Extract flat capabilities from wp-config-geodineum.yaml → shell variables
extract_flat_capabilities() {
    local file="$1"

    # Parse YAML capabilities section into key=value pairs
    # Only read lines under capabilities: until next top-level key
    local in_caps=false
    while IFS= read -r line; do
        # Start capturing at capabilities:
        if [[ "$line" =~ ^capabilities: ]]; then
            in_caps=true
            continue
        fi
        # Stop at next top-level key (no leading whitespace)
        if [[ "$in_caps" == "true" ]] && [[ "$line" =~ ^[a-z] ]]; then
            break
        fi
        # Skip comments and empty lines
        if [[ "$in_caps" == "true" ]]; then
            local trimmed
            trimmed=$(echo "$line" | sed 's/^\s*//' | sed 's/#.*//' | tr -d '"' | tr -d "'")
            [[ -z "$trimmed" ]] && continue
            # Parse key: value
            local key val
            key=$(echo "$trimmed" | cut -d: -f1 | tr -d ' ')
            val=$(echo "$trimmed" | cut -d: -f2- | sed 's/^\s*//')
            [[ -z "$key" || -z "$val" ]] && continue
            echo "${key}=${val}"
        fi
    done < "$file"
}

# Extract metadata fields (site_id, description, type, tier)
extract_metadata() {
    local file="$1"
    local in_meta=false
    while IFS= read -r line; do
        if [[ "$line" =~ ^metadata: ]]; then
            in_meta=true
            continue
        fi
        if [[ "$in_meta" == "true" ]] && [[ "$line" =~ ^[a-z] ]]; then
            break
        fi
        if [[ "$in_meta" == "true" ]]; then
            local trimmed
            trimmed=$(echo "$line" | sed 's/^\s*//' | sed 's/#.*//' | tr -d '"' | tr -d "'")
            [[ -z "$trimmed" ]] && continue
            local key val
            key=$(echo "$trimmed" | cut -d: -f1 | tr -d ' ')
            val=$(echo "$trimmed" | cut -d: -f2- | sed 's/^\s*//')
            [[ -z "$key" || -z "$val" ]] && continue
            echo "${key}=${val}"
        fi
    done < "$file"
}

# Generate gnode_services.yaml from CAP_* variables
generate_services_yaml() {
    local site_id="$1"
    local output_file="$2"
    local description="${3:-Geodineum service}"
    local tier="${4:-SERVICE}"
    local service_type="${5:-service}"
    local lang="${6:-}"
    # Reads CAP_* variables from environment

    cat > "$output_file" << YAMLEOF
# gNode Service Configuration
# Generated by: geodineum register ${site_id}
# Auto-generated from capabilities — edit to refine.
# The daemon discovers this file via discovery-paths.conf.
# Changes detected within ~120s (or restart daemon).

services:
  - id: "${site_id}"
    metadata:
      description: "${description}"
      type: "${service_type}"
      tier: "${tier}"${lang:+
      language: "${lang}"}
      created_by: "geodineum-register"
    capabilities:
      - name: "protocol"
        value: "${CAP_PROTOCOL:-http_rest}"
      - name: "native_format"
        value: "${CAP_FORMAT:-json}"
      - name: "api_version"
        value: "${CAP_API_VERSION:-v1}"
      - name: "contract_stability"
        value: "${CAP_STABILITY:-stable}"
      - name: "clearance_required"
        value: "${CAP_CLEARANCE:-public}"
      - name: "auth_method"
        value: "${CAP_AUTH:-session_cookie}"
      - name: "data_sensitivity"
        value: "${CAP_SENSITIVITY:-internal}"
      - name: "service_scope"
        value: "${CAP_SCOPE:-client_facing}"
      - name: "domain_primary"
        value: "${CAP_DOMAIN:-content}"
      - name: "domain_secondary"
        value: "${CAP_DOMAIN_SECONDARY:-template}"
      - name: "specialization"
        value: "${CAP_SPECIALIZATION:-generalist}"
      - name: "throughput_tier"
        value: "${CAP_THROUGHPUT:-standard}"
      - name: "latency_class"
        value: "${CAP_LATENCY:-responsive}"
      - name: "reliability_tier"
        value: "${CAP_RELIABILITY:-standard}"
      - name: "pipeline_stage"
        value: "${CAP_PIPELINE_STAGE:-deliver}"
      - name: "execution_priority"
        value: "${CAP_PRIORITY:-normal}"
      - name: "service_tier"
        value: "${tier}"
      - name: "environment"
        value: "${CAP_ENVIRONMENT:-production}"
YAMLEOF
}

# Map flat YAML key names to CAP_* variable names
map_flat_key_to_cap() {
    local key="$1"
    case "$key" in
        protocol)           echo "CAP_PROTOCOL" ;;
        native_format)      echo "CAP_FORMAT" ;;
        api_version)        echo "CAP_API_VERSION" ;;
        contract_stability) echo "CAP_STABILITY" ;;
        clearance_required) echo "CAP_CLEARANCE" ;;
        auth_method)        echo "CAP_AUTH" ;;
        data_sensitivity)   echo "CAP_SENSITIVITY" ;;
        service_scope)      echo "CAP_SCOPE" ;;
        domain_primary)     echo "CAP_DOMAIN" ;;
        domain_secondary)   echo "CAP_DOMAIN_SECONDARY" ;;
        specialization)     echo "CAP_SPECIALIZATION" ;;
        throughput_tier)    echo "CAP_THROUGHPUT" ;;
        latency_class)      echo "CAP_LATENCY" ;;
        reliability_tier)   echo "CAP_RELIABILITY" ;;
        pipeline_stage)     echo "CAP_PIPELINE_STAGE" ;;
        execution_priority) echo "CAP_PRIORITY" ;;
        *)                  echo "" ;;
    esac
}

# =============================================================================
# Express Mode — Capability Inference from Service Root
# =============================================================================

# Detect dominant programming language from project files
express_detect_language() {
    local path="$1"

    # Check for definitive project files first
    [[ -f "${path}/composer.json" ]] && { echo "php"; return 0; }
    [[ -f "${path}/wp-config.php" ]] && { echo "php"; return 0; }
    [[ -f "${path}/Cargo.toml" ]] && { echo "rust"; return 0; }
    [[ -f "${path}/go.mod" ]] && { echo "go"; return 0; }
    [[ -f "${path}/pyproject.toml" ]] && { echo "python"; return 0; }
    [[ -f "${path}/requirements.txt" ]] && { echo "python"; return 0; }
    [[ -f "${path}/setup.py" ]] && { echo "python"; return 0; }
    [[ -f "${path}/package.json" ]] && { echo "node"; return 0; }
    [[ -f "${path}/Gemfile" ]] && { echo "ruby"; return 0; }
    [[ -f "${path}/build.gradle" ]] || [[ -f "${path}/pom.xml" ]] && { echo "java"; return 0; }

    # Fall back to file extension counting (depth-limited)
    local counts=()
    local php_n py_n js_n rs_n go_n
    php_n=$(find "$path" -maxdepth 3 -name "*.php" 2>/dev/null | head -100 | wc -l)
    py_n=$(find "$path" -maxdepth 3 -name "*.py" 2>/dev/null | head -100 | wc -l)
    js_n=$(find "$path" -maxdepth 3 \( -name "*.js" -o -name "*.ts" \) -not -path "*/node_modules/*" 2>/dev/null | head -100 | wc -l)
    rs_n=$(find "$path" -maxdepth 3 -name "*.rs" 2>/dev/null | head -100 | wc -l)
    go_n=$(find "$path" -maxdepth 3 -name "*.go" 2>/dev/null | head -100 | wc -l)

    local max=0 lang="unknown"
    for pair in "php:${php_n}" "python:${py_n}" "node:${js_n}" "rust:${rs_n}" "go:${go_n}"; do
        local l="${pair%%:*}" n="${pair##*:}"
        if [[ $n -gt $max ]]; then
            max=$n
            lang="$l"
        fi
    done

    echo "$lang"
}

# Detect framework from project files
express_detect_framework() {
    local path="$1"
    local lang="$2"

    case "$lang" in
        php)
            [[ -f "${path}/wp-config.php" ]] || [[ -f "${path}/wp-load.php" ]] && { echo "wordpress"; return 0; }
            grep -q '"laravel/framework"' "${path}/composer.json" 2>/dev/null && { echo "laravel"; return 0; }
            grep -q '"symfony/framework-bundle"' "${path}/composer.json" 2>/dev/null && { echo "symfony"; return 0; }
            grep -q '"slim/slim"' "${path}/composer.json" 2>/dev/null && { echo "slim"; return 0; }
            echo "php-generic"
            ;;
        python)
            grep -qi "fastapi" "${path}/requirements.txt" "${path}/pyproject.toml" 2>/dev/null && { echo "fastapi"; return 0; }
            grep -qi "django" "${path}/requirements.txt" "${path}/pyproject.toml" 2>/dev/null && { echo "django"; return 0; }
            grep -qi "flask" "${path}/requirements.txt" "${path}/pyproject.toml" 2>/dev/null && { echo "flask"; return 0; }
            echo "python-generic"
            ;;
        node)
            grep -q '"next"' "${path}/package.json" 2>/dev/null && { echo "nextjs"; return 0; }
            grep -q '"express"' "${path}/package.json" 2>/dev/null && { echo "express"; return 0; }
            grep -q '"fastify"' "${path}/package.json" 2>/dev/null && { echo "fastify"; return 0; }
            grep -q '"@nestjs/core"' "${path}/package.json" 2>/dev/null && { echo "nestjs"; return 0; }
            echo "node-generic"
            ;;
        rust)
            grep -q 'axum' "${path}/Cargo.toml" 2>/dev/null && { echo "axum"; return 0; }
            grep -q 'actix' "${path}/Cargo.toml" 2>/dev/null && { echo "actix"; return 0; }
            grep -q 'rocket' "${path}/Cargo.toml" 2>/dev/null && { echo "rocket"; return 0; }
            grep -q 'tokio' "${path}/Cargo.toml" 2>/dev/null && { echo "rust-async"; return 0; }
            echo "rust-generic"
            ;;
        go)
            grep -q 'gin-gonic' "${path}/go.mod" 2>/dev/null && { echo "gin"; return 0; }
            grep -q 'labstack/echo' "${path}/go.mod" 2>/dev/null && { echo "echo"; return 0; }
            grep -q 'go-chi/chi' "${path}/go.mod" 2>/dev/null && { echo "chi"; return 0; }
            echo "go-generic"
            ;;
        *)
            echo "generic"
            ;;
    esac
}

# Detect API protocol from project structure
express_detect_protocol() {
    local path="$1"
    local framework="$2"

    # Framework-specific defaults
    case "$framework" in
        wordpress|laravel|symfony|slim|django|flask|express|fastify|nextjs|nestjs|gin|echo|chi|axum|actix|rocket)
            echo "http_rest"
            return 0
            ;;
    esac

    # Check for GraphQL
    if find "$path" -maxdepth 3 \( -name "*.graphql" -o -name "schema.graphqls" \) 2>/dev/null | head -1 | grep -q .; then
        echo "graphql"
        return 0
    fi

    # Check for gRPC / protobuf
    if find "$path" -maxdepth 3 -name "*.proto" 2>/dev/null | head -1 | grep -q .; then
        echo "grpc"
        return 0
    fi

    # Check for stream-based (gNode integration)
    if grep -rq "xadd\|XADD\|xreadgroup\|XREADGROUP\|gnode_stream" "$path" --include="*.php" --include="*.py" --include="*.rs" --include="*.go" --include="*.js" -l 2>/dev/null | head -1 | grep -q .; then
        echo "gnode_stream"
        return 0
    fi

    echo "http_rest"
}

# Detect service scope from project structure
express_detect_scope() {
    local path="$1"
    local framework="$2"

    # WordPress and web frameworks are client-facing
    case "$framework" in
        wordpress|laravel|django|nextjs|symfony)
            echo "client_facing"
            return 0
            ;;
    esac

    # Check for systemd service (daemon)
    if find /etc/systemd/system/ -name "*.service" -exec grep -l "$path" {} \; 2>/dev/null | head -1 | grep -q .; then
        echo "daemon"
        return 0
    fi

    # Check for queue/worker patterns
    if grep -rq "consumer\|worker\|queue\|celery\|supervisor" "$path" --include="*.py" --include="*.php" --include="*.yaml" --include="*.conf" -l 2>/dev/null | head -1 | grep -q .; then
        echo "worker"
        return 0
    fi

    # Check for CLI tool
    if [[ -f "${path}/bin/console" ]] || [[ -d "${path}/cli" ]]; then
        echo "worker"
        return 0
    fi

    # Default for web-accessible paths
    if [[ "$path" == /var/www/* ]]; then
        echo "client_facing"
        return 0
    fi

    echo "daemon"
}

# Detect log file location
express_detect_logs() {
    local path="$1"

    for candidate in \
        "${path}/storage/logs" \
        "${path}/var/log" \
        "${path}/logs" \
        "${path}/log" \
        "/var/log/$(basename "$path")"; do
        if [[ -d "$candidate" ]]; then
            echo "$candidate"
            return 0
        fi
    done

    echo ""
}

# Detect documentation location
express_detect_docs() {
    local path="$1"

    for candidate in \
        "${path}/docs" \
        "${path}/doc" \
        "${path}/documentation" \
        "${path}/wiki"; do
        if [[ -d "$candidate" ]]; then
            echo "$candidate"
            return 0
        fi
    done

    # Check for README
    if [[ -f "${path}/README.md" ]] || [[ -f "${path}/README.rst" ]]; then
        echo "${path}"
        return 0
    fi

    echo ""
}

# Detect native data format
express_detect_format() {
    local path="$1"
    local framework="$2"

    case "$framework" in
        wordpress|laravel|django|flask|express|fastify|nextjs|nestjs)
            echo "json"
            return 0
            ;;
    esac

    # Check for XML-heavy codebases
    local xml_n json_n
    xml_n=$(find "$path" -maxdepth 2 -name "*.xml" -not -path "*/.git/*" 2>/dev/null | head -20 | wc -l)
    json_n=$(find "$path" -maxdepth 2 -name "*.json" -not -path "*/.git/*" -not -path "*/node_modules/*" 2>/dev/null | head -20 | wc -l)
    if [[ $xml_n -gt $json_n ]] && [[ $xml_n -gt 5 ]]; then
        echo "xml"
        return 0
    fi

    echo "json"
}

# Map framework to sensible capability defaults
express_map_framework_capabilities() {
    local framework="$1"
    local lang="$2"

    # These set reasonable defaults; the user can override in confirmation
    case "$framework" in
        wordpress)
            CAP_DOMAIN="content"
            CAP_DOMAIN_SECONDARY="template"
            CAP_LATENCY="responsive"
            CAP_THROUGHPUT="professional"
            CAP_RELIABILITY="high"
            CAP_STABILITY="stable"
            CAP_CLEARANCE="public"
            CAP_AUTH="session_cookie"
            CAP_SPECIALIZATION="generalist"
            CAP_PIPELINE_STAGE="deliver"
            ;;
        laravel|symfony|django)
            CAP_DOMAIN="content"
            CAP_DOMAIN_SECONDARY="platform"
            CAP_LATENCY="interactive"
            CAP_THROUGHPUT="professional"
            CAP_RELIABILITY="high"
            CAP_STABILITY="stable"
            CAP_CLEARANCE="authenticated"
            CAP_AUTH="bearer_token"
            CAP_SPECIALIZATION="focused"
            CAP_PIPELINE_STAGE="process"
            ;;
        flask|express|fastify|slim|gin|echo|chi|axum|actix|rocket)
            CAP_DOMAIN="compute"
            CAP_DOMAIN_SECONDARY="platform"
            CAP_LATENCY="interactive"
            CAP_THROUGHPUT="standard"
            CAP_RELIABILITY="standard"
            CAP_STABILITY="beta"
            CAP_CLEARANCE="authenticated"
            CAP_AUTH="bearer_token"
            CAP_SPECIALIZATION="focused"
            CAP_PIPELINE_STAGE="process"
            ;;
        fastapi)
            CAP_DOMAIN="compute"
            CAP_DOMAIN_SECONDARY="platform"
            CAP_LATENCY="responsive"
            CAP_THROUGHPUT="professional"
            CAP_RELIABILITY="high"
            CAP_STABILITY="stable"
            CAP_CLEARANCE="authenticated"
            CAP_AUTH="bearer_token"
            CAP_SPECIALIZATION="specialist"
            CAP_PIPELINE_STAGE="process"
            ;;
        nextjs|nestjs)
            CAP_DOMAIN="content"
            CAP_DOMAIN_SECONDARY="template"
            CAP_LATENCY="responsive"
            CAP_THROUGHPUT="professional"
            CAP_RELIABILITY="high"
            CAP_STABILITY="stable"
            CAP_CLEARANCE="public"
            CAP_AUTH="bearer_token"
            CAP_SPECIALIZATION="generalist"
            CAP_PIPELINE_STAGE="deliver"
            ;;
        *)
            CAP_DOMAIN="compute"
            CAP_DOMAIN_SECONDARY="platform"
            CAP_LATENCY="responsive"
            CAP_THROUGHPUT="standard"
            CAP_RELIABILITY="standard"
            CAP_STABILITY="beta"
            CAP_CLEARANCE="authenticated"
            CAP_AUTH="bearer_token"
            CAP_SPECIALIZATION="generalist"
            CAP_PIPELINE_STAGE="process"
            ;;
    esac

    CAP_SENSITIVITY="internal"
    CAP_PRIORITY="normal"
}

# Run full express detection and set CAP_* variables
express_detect_all() {
    local path="$1"

    log_step "Express Mode: Scanning ${path}"

    # Language
    EXPRESS_LANG=$(express_detect_language "$path")
    log_detail "Language:  ${EXPRESS_LANG}"

    # Framework
    EXPRESS_FRAMEWORK=$(express_detect_framework "$path" "$EXPRESS_LANG")
    log_detail "Framework: ${EXPRESS_FRAMEWORK}"

    # Protocol
    CAP_PROTOCOL=$(express_detect_protocol "$path" "$EXPRESS_FRAMEWORK")
    log_detail "Protocol:  ${CAP_PROTOCOL}"

    # Format
    CAP_FORMAT=$(express_detect_format "$path" "$EXPRESS_FRAMEWORK")
    log_detail "Format:    ${CAP_FORMAT}"

    # Scope
    CAP_SCOPE=$(express_detect_scope "$path" "$EXPRESS_FRAMEWORK")
    log_detail "Scope:     ${CAP_SCOPE}"

    # Framework-based defaults
    express_map_framework_capabilities "$EXPRESS_FRAMEWORK" "$EXPRESS_LANG"

    # Logs and docs (metadata, not topology dimensions)
    EXPRESS_LOGS=$(express_detect_logs "$path")
    EXPRESS_DOCS=$(express_detect_docs "$path")
    [[ -n "$EXPRESS_LOGS" ]] && log_detail "Logs:      ${EXPRESS_LOGS}"
    [[ -n "$EXPRESS_DOCS" ]] && log_detail "Docs:      ${EXPRESS_DOCS}"

    echo ""
}

# Interactive confirmation of detected capabilities
express_confirm() {
    echo -e "  ${BOLD}Detected Capabilities${NC}"
    echo -e "  ${DIM}─────────────────────────────────────────────${NC}"
    printf "  ${DIM}%-24s${NC} %s\n" "protocol:" "$CAP_PROTOCOL"
    printf "  ${DIM}%-24s${NC} %s\n" "native_format:" "$CAP_FORMAT"
    printf "  ${DIM}%-24s${NC} %s\n" "service_scope:" "$CAP_SCOPE"
    printf "  ${DIM}%-24s${NC} %s\n" "domain_primary:" "$CAP_DOMAIN"
    printf "  ${DIM}%-24s${NC} %s\n" "domain_secondary:" "$CAP_DOMAIN_SECONDARY"
    printf "  ${DIM}%-24s${NC} %s\n" "specialization:" "$CAP_SPECIALIZATION"
    printf "  ${DIM}%-24s${NC} %s\n" "throughput_tier:" "$CAP_THROUGHPUT"
    printf "  ${DIM}%-24s${NC} %s\n" "latency_class:" "$CAP_LATENCY"
    printf "  ${DIM}%-24s${NC} %s\n" "reliability_tier:" "$CAP_RELIABILITY"
    printf "  ${DIM}%-24s${NC} %s\n" "contract_stability:" "$CAP_STABILITY"
    printf "  ${DIM}%-24s${NC} %s\n" "clearance_required:" "$CAP_CLEARANCE"
    printf "  ${DIM}%-24s${NC} %s\n" "auth_method:" "$CAP_AUTH"
    printf "  ${DIM}%-24s${NC} %s\n" "data_sensitivity:" "$CAP_SENSITIVITY"
    printf "  ${DIM}%-24s${NC} %s\n" "pipeline_stage:" "$CAP_PIPELINE_STAGE"
    printf "  ${DIM}%-24s${NC} %s\n" "execution_priority:" "$CAP_PRIORITY"
    echo ""

    # Auto-accept if not interactive (piped input or --force)
    if [[ ! -t 0 ]]; then
        log_info "Non-interactive — accepting detected capabilities"
        return
    fi

    echo -en "  Proceed with these capabilities? [${BOLD}Y${NC}/n/e(dit)] "
    local answer
    read -r answer < /dev/tty

    case "${answer,,}" in
        n|no)
            log_info "Registration cancelled"
            exit 0
            ;;
        e|edit)
            express_edit_capabilities
            ;;
        *)
            # Accept
            ;;
    esac
}

# Interactive editing of individual capabilities
express_edit_capabilities() {
    local -a dims=(
        "CAP_PROTOCOL:protocol"
        "CAP_FORMAT:native_format"
        "CAP_SCOPE:service_scope"
        "CAP_DOMAIN:domain_primary"
        "CAP_DOMAIN_SECONDARY:domain_secondary"
        "CAP_SPECIALIZATION:specialization"
        "CAP_THROUGHPUT:throughput_tier"
        "CAP_LATENCY:latency_class"
        "CAP_RELIABILITY:reliability_tier"
        "CAP_STABILITY:contract_stability"
        "CAP_CLEARANCE:clearance_required"
        "CAP_AUTH:auth_method"
        "CAP_SENSITIVITY:data_sensitivity"
        "CAP_PIPELINE_STAGE:pipeline_stage"
        "CAP_PRIORITY:execution_priority"
    )

    echo ""
    echo -e "  ${BOLD}Edit capabilities${NC} (press Enter to keep current value)"
    echo ""

    for entry in "${dims[@]}"; do
        local var="${entry%%:*}"
        local name="${entry##*:}"
        local current="${!var}"

        echo -en "  ${name} [${DIM}${current}${NC}]: "
        local new_val
        read -r new_val < /dev/tty

        if [[ -n "$new_val" ]]; then
            export "$var=$new_val"
        fi
    done

    echo ""
    log_info "Capabilities updated"
}

# =============================================================================
# geodineum register
# =============================================================================

cmd_register() {
    local site_id=""
    local yaml_file=""
    local template=""
    local environment="testing"
    local owner=""
    local service_path=""
    local notify_email=""
    local express=false
    local dry_run=false
    local force=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --yaml)         yaml_file="$2"; shift 2 ;;
            --template)     template="$2"; shift 2 ;;
            --env)          environment="$2"; shift 2 ;;
            --owner)        owner="$2"; shift 2 ;;
            --path)         service_path="$2"; shift 2 ;;
            --notify-email) notify_email="$2"; shift 2 ;;
            --express)      express=true; shift ;;
            --dry-run)      dry_run=true; shift ;;
            --force)        force=true; shift ;;
            --help|-h)  usage_register; exit 0 ;;
            -*)         log_error "Unknown option: $1"; exit 1 ;;
            *)
                if [[ -z "$site_id" ]]; then
                    site_id="$1"
                else
                    log_error "Unexpected argument: $1"
                    exit 1
                fi
                shift
                ;;
        esac
    done

    if [[ -z "$site_id" ]]; then
        log_error "Site/service ID is required"
        usage_register
        exit 1
    fi

    validate_site_id "$site_id" || exit 1
    validate_environment "$environment" || exit 1

    # =================================================================
    # Resolve service path (required for .geodineum/)
    # =================================================================

    if [[ -z "$service_path" ]]; then
        service_path=$(resolve_service_path "$site_id") || true
    fi

    if [[ -z "$service_path" ]]; then
        log_error "Cannot determine service path for '${site_id}'"
        log_error "Specify --path <service_root_directory>"
        exit 1
    fi

    if [[ ! -d "$service_path" ]]; then
        log_error "Service path does not exist: ${service_path}"
        exit 1
    fi

    local geodineum_dir="${service_path}/.geodineum"

    # =================================================================
    # Resolve capabilities source
    # =================================================================

    local cap_source="default"
    local description="Geodineum service"
    local tier="SERVICE"
    local service_type="service"
    local detected_lang=""

    if [[ "$express" == "true" ]]; then
        cap_source="express"
        express_detect_all "$service_path"
        detected_lang="$EXPRESS_LANG"

        # Infer description and tier from framework
        case "$EXPRESS_FRAMEWORK" in
            wordpress)
                description="WordPress site (${EXPRESS_FRAMEWORK})"
                service_type="wordpress-site"
                ;;
            *)
                description="${EXPRESS_FRAMEWORK} service (${EXPRESS_LANG})"
                service_type="standalone-service"
                ;;
        esac

    elif [[ -n "$yaml_file" ]]; then
        if [[ ! -f "$yaml_file" ]]; then
            log_error "YAML file not found: ${yaml_file}"
            exit 1
        fi

        local format
        format=$(detect_yaml_format "$yaml_file")

        case "$format" in
            flat)
                cap_source="flat-yaml"
                while IFS='=' read -r key val; do
                    local cap_var
                    cap_var=$(map_flat_key_to_cap "$key")
                    if [[ -n "$cap_var" ]]; then
                        export "$cap_var=$val"
                    fi
                done < <(extract_flat_capabilities "$yaml_file")

                while IFS='=' read -r key val; do
                    case "$key" in
                        type)        service_type="$val" ;;
                        description) description="$val" ;;
                        theme)       description="WordPress site (${val} theme)" ;;
                    esac
                done < <(extract_metadata "$yaml_file")

                case "$service_type" in
                    wordpress-site) tier="SERVICE" ;;
                    pipeline) tier="PIPELINE" ;;
                    *) tier="SERVICE" ;;
                esac
                ;;

            daemon)
                cap_source="daemon-yaml"
                ;;

            *)
                log_warning "Unknown YAML format in ${yaml_file} — using defaults"
                ;;
        esac

    elif [[ -n "$template" ]]; then
        cap_source="template"
        source "${GEODINEUM_CLI_ROOT}/lib/service.sh" 2>/dev/null || true
        apply_preset "$template"
    fi

    # =================================================================
    # Banner
    # =================================================================

    echo ""
    echo -e "${CYAN}╔══════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║${NC}           ${BOLD}Geodineum Service Registration${NC}                          ${CYAN}║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════════════════════════════════╝${NC}"
    echo ""

    print_kv "Site ID" "$site_id"
    print_kv "Service path" "$service_path"
    print_kv "Environment" "$environment"
    print_kv "Capabilities" "$cap_source"
    [[ -n "$yaml_file" ]] && print_kv "Source YAML" "$yaml_file"
    [[ -n "$template" ]] && print_kv "Template" "$template"
    [[ -n "$detected_lang" ]] && print_kv "Language" "$detected_lang"
    [[ -n "$owner" ]] && print_kv "Owner" "$owner"
    [[ -n "$notify_email" ]] && print_kv "Notify Email" "$notify_email"
    print_kv ".geodineum" "$geodineum_dir"
    echo ""

    # Express confirmation (interactive)
    if [[ "$express" == "true" ]] && [[ "$dry_run" != "true" ]]; then
        express_confirm
    fi

    # =================================================================
    # Notification email prompt (interactive)
    # =================================================================

    if [[ -z "$notify_email" ]] && [[ "$dry_run" != "true" ]] && [[ -t 0 ]]; then
        local domain="${site_id//_/.}"
        local default_email="admin@${domain}"
        echo ""
        read -rp "$(echo -e "${BLUE}[?]${NC} Notification email? [${default_email}]: ")" notify_email
        notify_email="${notify_email:-$default_email}"
        echo ""
    fi

    # =================================================================
    # Dry-run
    # =================================================================

    if [[ "$dry_run" == "true" ]]; then
        log_step "Dry-Run Summary"
        log_dry "Create ${geodineum_dir}/ (credentials/, config.yaml)"
        log_dry "Generate gnode_services.yaml in .geodineum/"
        log_dry "Run onboard-service.sh for ACL + streams + registry"
        log_dry "Finalize .geodineum/ (credential symlink, .registered marker)"
        if [[ -f "${service_path}/wp-config.php" ]] || [[ -f "${service_path}/wp-load.php" ]]; then
            log_dry "Wire WordPress integration (gCore mu-plugin + gTemplate parent theme)"
        fi
        log_dry "Register .geodineum in discovery-paths.conf"
        [[ -n "$owner" ]] && log_dry "Set tenant owner: ${owner}"
        [[ -n "$notify_email" ]] && log_dry "Configure COMMS email → ${notify_email}"
        echo ""
        log_info "No changes made (dry-run mode)"
        return 0
    fi

    require_sudo "Service registration"

    # =================================================================
    # Step 1/4: Create .geodineum/ directory
    # =================================================================

    log_step "Step 1/4: Creating .geodineum/"

    if [[ -d "$geodineum_dir" ]] && [[ "$force" != "true" ]]; then
        log_info ".geodineum/ already exists (use --force to recreate)"
    else
        create_geodineum_dir "$service_path" "$site_id" "$environment" || {
            log_error "Failed to create .geodineum/"
            exit 1
        }
    fi

    # Generate unified config.yaml (identity + environment + valkey + capabilities)
    if [[ ! -f "${geodineum_dir}/config.yaml" ]] || [[ "$force" == "true" ]]; then
        CAP_ENVIRONMENT="$environment"
        generate_geodineum_config "$service_path" "$site_id" "$environment" \
            "$description" "$service_type" "$tier" "$detected_lang"
    else
        log_info "config.yaml already exists (use --force to regenerate)"
    fi

    # Generate gnode_services.yaml inside .geodineum/
    local services_yaml="${geodineum_dir}/gnode_services.yaml"

    if [[ -f "$services_yaml" ]] && [[ "$force" != "true" ]]; then
        log_success "gnode_services.yaml already exists (use --force to regenerate)"
    else
        case "$cap_source" in
            daemon-yaml)
                cp "$yaml_file" "$services_yaml"
                log_success "Copied daemon-format YAML to .geodineum/"
                ;;
            flat-yaml|template|default|express)
                CAP_ENVIRONMENT="$environment"
                generate_services_yaml "$site_id" "$services_yaml" \
                    "$description" "$tier" "$service_type" "$detected_lang"
                log_success "Generated gnode_services.yaml (${cap_source})"
                ;;
        esac
    fi

    # Show capabilities
    log_detail "Capabilities:"
    grep "value:" "$services_yaml" 2>/dev/null | while IFS= read -r line; do
        log_detail "  $(echo "$line" | sed 's/.*value: *//' | tr -d '"')"
    done

    # =================================================================
    # Step 2/4: Onboard (ACL + streams + registry + broadcast)
    # =================================================================

    log_step "Step 2/4: Onboarding (ACL + Streams + Registry)"

    require_gnode

    local onboard_script="${GNODE_SCRIPTS}/onboard-service.sh"
    local onboard_args=("$site_id" --environment "$environment")

    [[ -n "$owner" ]] && onboard_args+=(--owner "$owner")
    [[ -n "$notify_email" ]] && onboard_args+=(--notify-email "$notify_email")
    [[ "$force" == "true" ]] && onboard_args+=(--force)

    # Point onboard at .geodineum/ for discovery-paths.conf
    onboard_args+=(--yaml "$geodineum_dir")

    log_detail "Running: ${onboard_script} ${onboard_args[*]}"
    "$onboard_script" "${onboard_args[@]}" || {
        log_error "Onboarding failed — see output above"
        exit 1
    }

    # =================================================================
    # Step 3/4: Finalize .geodineum/ (credentials + marker)
    # =================================================================

    log_step "Step 3/4: Finalizing .geodineum/"

    finalize_geodineum_dir "$service_path" "$site_id" "$environment" || {
        log_warning "Could not finalize .geodineum/ — credentials may not be symlinked"
    }

    # =================================================================
    # WordPress integration (mu-plugin + parent theme)
    # =================================================================

    # Detect WordPress and wire up gCore + gTemplate if present
    if [[ -f "${service_path}/wp-config.php" ]] || [[ -f "${service_path}/wp-load.php" ]]; then
        log_step "WordPress Integration (mu-plugin + parent theme)"
        setup_wordpress_integration "$service_path"
    fi

    # =================================================================
    # Step 4/4: Verify daemon will discover this
    # =================================================================

    log_step "Step 4/4: Discovery Verification"

    local disc_conf="$GEODINEUM_DISCOVERY_CONF"
    if [[ -f "$disc_conf" ]] && grep -q "$geodineum_dir" "$disc_conf" 2>/dev/null; then
        log_success "Config dir registered in discovery-paths.conf"
    else
        log_warning "Config dir NOT in discovery-paths.conf — daemon may not discover capabilities"
        log_info "The onboard script should have added it. Check: cat ${disc_conf}"
    fi

    if systemctl is-active --quiet gnode-daemon 2>/dev/null; then
        log_success "Daemon is running — will discover capabilities within 120s"
        log_info "For immediate discovery: sudo systemctl restart gnode-daemon"
    else
        log_warning "Daemon not running — capabilities will be discovered on next start"
    fi

    # =================================================================
    # Express: offer app config import
    # =================================================================

    if [[ "$express" == "true" ]]; then
        local config_files
        config_files=$(scan_config_files "$service_path" 2>/dev/null) || config_files=""
        if [[ -n "$config_files" ]]; then
            local cf_count
            cf_count=$(echo "$config_files" | wc -l)
            echo ""
            echo -en "  Found ${cf_count} config file(s). Import app config to ValKey? [y/${BOLD}N${NC}] "
            local answer
            read -r answer < /dev/tty 2>/dev/null || answer="n"
            if [[ "${answer,,}" == "y" || "${answer,,}" == "yes" ]]; then
                source "${GEODINEUM_CLI_ROOT}/lib/config.sh" 2>/dev/null || true
                cmd_config_import "$site_id" --path "$service_path" --force
            fi
        fi
    fi

    # =================================================================
    # Summary
    # =================================================================

    print_summary_header "Service Registered Successfully"

    print_kv "Site ID" "$site_id"
    print_kv "Environment" "$environment"
    print_kv ".geodineum" "$geodineum_dir"
    print_kv "Credentials" "${geodineum_dir}/credentials/valkey_client_${site_id}.password"
    print_kv "Config" "${services_yaml}"
    print_kv "Capabilities" "$(grep -c "name:" "$services_yaml" 2>/dev/null || echo 0) dimensions"
    [[ -n "${EXPRESS_LOGS:-}" ]] && print_kv "Log location" "$EXPRESS_LOGS"
    [[ -n "${EXPRESS_DOCS:-}" ]] && print_kv "Docs location" "$EXPRESS_DOCS"
    echo ""

    echo -e "  ${BOLD}What happens next:${NC}"
    echo "    1. Daemon discovers capabilities within 120s (or restart for immediate)"
    echo "    2. Service appears in 23D topology (geodineum info ${site_id})"
    echo "    3. Other services can discover it via geometric_discover"
    echo ""
}

# =============================================================================
# Usage
# =============================================================================

usage_register() {
    cat << 'EOF'
Usage: geodineum register <site_id> [options]

Register an existing service into the Geodineum ecosystem.
Creates .geodineum/ directory, ACL user, streams, site registry entry,
and capability configuration for 23D topology discovery.

This is the ONLY registration path. Theme-side registration is removed.

Arguments:
  <site_id>                 Service identifier (lowercase, a-z0-9_)

Capability sources (pick one):
  --express                 Auto-detect capabilities by scanning the service root
                            Infers: language, framework, protocol, scope, and more
  --yaml <path>             Read capabilities from YAML file (auto-detects format)
                            Supports: wp-config-geodineum.yaml (flat) or gnode_services.yaml (daemon)
  --template <preset>       Use capability preset: wordpress, http-api, worker, inference

Options:
  --path <service_dir>      Service root directory (auto-detected for WordPress sites)
  --env <environment>       DTAP environment (default: testing)
  --owner <tenant_id>       Tenant/owner for cross-site discovery
  --notify-email <email>    Notification recipient (configures COMMS email channel)
                            If omitted, prompts interactively (default: admin@{domain})
  --force                   Regenerate ACL password and overwrite existing config
  --dry-run                 Preview without making changes
  --help, -h                Show this help message

Examples:
  # Register existing WordPress site (reads capabilities from config)
  sudo geodineum register your_site --yaml /var/www/your-site/wp-config-geodineum.yaml --env production

  # Register with COMMS email notification
  sudo geodineum register your_site --express --path /var/www/your-site --notify-email admin@example.com

  # Express mode: scan and infer capabilities automatically
  sudo geodineum register my_api --express --path /opt/apps/my-api --env production

  # Register standalone service with preset
  sudo geodineum register my_api --template http-api --path /opt/services/my_api --env testing

  # Register with tenant grouping
  sudo geodineum register client_app --express --path /opt/apps/client --owner acme --env production

  # Preview what would happen
  geodineum register new_service --template worker --path /opt/svc --dry-run
EOF
}
