<?php
/**
 * {{DOMAIN}} — form endpoint (generated by `geodineum service new`).
 *
 * Standalone producer on the Geodineum COMMS wire contract: the message shape
 * mirrors gNodeClient::queueCommsMessage field-for-field (scalar id/type/
 * timestamp/site_id/environment/priority + JSON-string sender/content/
 * metadata/dispatch), so the daemon consumes it like any other site's mail.
 * Extend the field list to your form; keep the wire shape.
 */

declare(strict_types=1);

const SITE_ID       = '{{SITE_ID}}';
// DTAP tier comes from a root-owned file so staging/production flips are an
// operator action, never a code edit. Absent/invalid file fails safe: staging
// (COMMS dry-runs everything that is not production).
const TIER_FILE     = '{{TIER_FILE}}';
const VALKEY_HOST   = '127.0.0.1';
const VALKEY_PORT   = {{VALKEY_PORT}};
const VALKEY_USER   = 'gnode_client_{{SITE_ID}}';
const PASSWORD_FILE = '{{CREDENTIAL_FILE}}';
const RATE_PER_IP_H = 5;
const RATE_GLOBAL_H = 30;
const MIN_FILL_MS   = 2500;

header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');

function respond(int $code, array $body): never {
    http_response_code($code);
    echo json_encode($body);
    exit;
}
function ok(): never  { respond(200, ['success' => true]); }
function fail(int $code, string $msg): never { respond($code, ['success' => false, 'error' => $msg]); }

if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') {
    fail(405, 'method');
}

$tier = trim((string) @file_get_contents(TIER_FILE));
$environment = in_array($tier, ['dev', 'test', 'testing', 'staging', 'acceptance', 'production'], true) ? $tier : 'staging';

$field = static fn(string $k): string => trim((string) ($_POST[$k] ?? ''));

// Honeypot and fill-time: bots get a silent "success" and nothing is stored.
if ($field('website') !== '') { ok(); }
$loadMs = (int) $field('_load_ms');
if ($loadMs > 0 && $loadMs < MIN_FILL_MS) { ok(); }

$name    = $field('name');
$email   = $field('email');
$phone   = $field('phone');
$subject = $field('subject');
$message = $field('message');

if ($name === '' || $email === '' || $message === '') {
    fail(422, 'missing');
}
if (!filter_var($email, FILTER_VALIDATE_EMAIL)) { fail(422, 'email'); }
if ($phone !== '' && !preg_match('/^[0-9+ .\-]{6,20}$/', $phone)) { fail(422, 'phone'); }
foreach ([$name, $subject] as $v) {
    if (mb_strlen($v) > 200) { fail(422, 'length'); }
}
if (mb_strlen($message) > 5000) { fail(422, 'length'); }

$vk = new Redis();
try {
    $pass = trim((string) @file_get_contents(PASSWORD_FILE));
    if ($pass === '') { throw new RuntimeException('no credential'); }
    $vk->connect(VALKEY_HOST, VALKEY_PORT, 3.0);
    $vk->auth([VALKEY_USER, $pass]);
} catch (Throwable $e) {
    error_log(SITE_ID . ' form: valkey unavailable');
    fail(503, 'backend');
}

$ip = $_SERVER['REMOTE_ADDR'] ?? '';
try {
    $ipKey = '{' . SITE_ID . '}:forms:ratelimit:' . hash('sha256', $ip);
    $n = $vk->incr($ipKey);
    if ($n === 1) { $vk->expire($ipKey, 3600); }
    $gKey = '{' . SITE_ID . '}:forms:ratelimit:global';
    $g = $vk->incr($gKey);
    if ($g === 1) { $vk->expire($gKey, 3600); }
    if ($n > RATE_PER_IP_H || $g > RATE_GLOBAL_H) { fail(429, 'rate'); }
} catch (RedisException $e) {
    error_log(SITE_ID . ' form: ratelimit error');
    fail(503, 'backend');
}

$id = bin2hex(random_bytes(16));
$now = date('c');
$bodyLines = [
    'Name:    ' . $name,
    'Email:   ' . $email,
];
if ($phone !== '')   { $bodyLines[] = 'Phone:   ' . $phone; }
if ($subject !== '') { $bodyLines[] = 'Subject: ' . $subject; }
$bodyLines[] = '';
$bodyLines[] = $message;

// Display names are DATA on this wire — never put parentheses/brackets in
// from_name expecting them to survive RFC 5322 parsing downstream.
$entry = [
    'id'          => $id,
    'type'        => 'form.contact',
    'timestamp'   => $now,
    'site_id'     => SITE_ID,
    'environment' => $environment,
    'priority'    => '3',
    'sender'      => json_encode(['name' => $name, 'email' => $email]),
    'content'     => json_encode([
        'subject' => 'Form submission — ' . ($subject !== '' ? $subject : SITE_ID),
        'body'    => implode("\n", $bodyLines),
    ]),
    'metadata'    => json_encode(['form_type' => 'contact', 'environment' => $environment, 'ip_hash' => hash('sha256', $ip)]),
    'dispatch'    => json_encode(['channels' => ['email'], 'status' => 'pending', 'attempts' => 0, 'last_attempt' => null, 'next_retry' => null]),
];

try {
    $stream = '{' . SITE_ID . '}:gnode:comms:' . $environment;
    $vk->xAdd($stream, '*', $entry);
    // Archive the raw submission in the site's own namespace (declared in
    // the manifest's produces list).
    $vk->setex('{' . SITE_ID . '}:forms:entry:' . $id, 30 * 86400, json_encode([
        'name' => $name, 'email' => $email, 'phone' => $phone,
        'subject' => $subject, 'message' => $message, 'at' => $now,
    ]));
} catch (Throwable $e) {
    error_log(SITE_ID . ' form: enqueue failed');
    fail(503, 'backend');
}

ok();
