<?php
/**
 * {{DOMAIN}} — cookieless visitor-analytics beacon (generated by `geodineum service new`).
 *
 * Standalone twin of gTemplate's analytics endpoint: the front-end beacon
 * POSTs {path, ref}; this resolves a daily-rotating visitor hash and a bot
 * flag server-side, then records the hit through the GNODE_ANALYTICS_HIT
 * Lua function — one atomic write at the data. No cookies, no persistent
 * identifier: the hash is sha256(ip|ua|Ymd|salt) truncated, so it cannot be
 * correlated across days. Read back with `geodineum visitors {{SITE_ID}}`.
 */

declare(strict_types=1);

const SITE_ID       = '{{SITE_ID}}';
const VALKEY_HOST   = '127.0.0.1';
const VALKEY_PORT   = {{VALKEY_PORT}};
const VALKEY_USER   = 'gnode_client_{{SITE_ID}}';
const PASSWORD_FILE = '{{CREDENTIAL_FILE}}';

http_response_code(202);
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
echo '{"ok":true}';
// The beacon never waits: respond first, record after the connection closes.
if (function_exists('fastcgi_finish_request')) {
    fastcgi_finish_request();
}

if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') {
    exit;
}

$raw = (string) file_get_contents('php://input');
$params = json_decode($raw, true);
if (!is_array($params)) { $params = $_POST; }

$path = isset($params['path']) ? (string) $params['path'] : '/';
$path = strtok($path, '#');
$path = preg_replace('/[\x00-\x1f]/', '', (string) $path);
$path = '/' . ltrim($path, '/');
if (strlen($path) > 300) { $path = substr($path, 0, 300); }

$ref = isset($params['ref']) ? (string) $params['ref'] : '';
$ref_host = '';
if ($ref !== '') {
    $rh = parse_url($ref, PHP_URL_HOST);
    if ($rh && strcasecmp((string) $rh, $_SERVER['HTTP_HOST'] ?? '') !== 0) {
        $ref_host = strtolower((string) preg_replace('/[^a-zA-Z0-9._-]/', '', (string) $rh));
        if (strlen($ref_host) > 120) { $ref_host = substr($ref_host, 0, 120); }
    }
}

$ua = (string) ($_SERVER['HTTP_USER_AGENT'] ?? '');
$is_bot = ($ua === '' || preg_match(
    '/bot|crawl|spider|slurp|bingpreview|facebookexternalhit|embedly|quora|pinterest|'
    . 'vkshare|W3C_Validator|headless|phantom|puppeteer|playwright|lighthouse|curl|wget|'
    . 'python-requests|go-http|okhttp|httpclient|scrapy|ahrefs|semrush|mj12|dotbot|petalbot|'
    . 'gptbot|ccbot|claudebot|bytespider|amazonbot|dataforseo/i',
    $ua
)) ? '1' : '0';

$remote = (string) ($_SERVER['REMOTE_ADDR'] ?? '0.0.0.0');
$is_local = in_array($remote, ['127.0.0.1', '::1'], true)
    || (bool) preg_match('/^(10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/', $remote);
if ($is_local && !empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
    $first = trim(explode(',', (string) $_SERVER['HTTP_X_FORWARDED_FOR'])[0]);
    if (filter_var($first, FILTER_VALIDATE_IP)) { $remote = $first; }
}

try {
    $pass = trim((string) @file_get_contents(PASSWORD_FILE));
    if ($pass === '') { exit; }
    $vk = new Redis();
    $vk->connect(VALKEY_HOST, VALKEY_PORT, 2.0);
    $vk->auth([VALKEY_USER, $pass]);

    $ymd = gmdate('Ymd');
    // Salt derives from the credential — server-side only, never emitted.
    $vhash = substr(hash('sha256', $remote . '|' . $ua . '|' . $ymd . '|' . hash('sha256', $pass)), 0, 24);

    $vk->fcall('GNODE_ANALYTICS_HIT', [], [
        SITE_ID, $vhash, $path, $ref_host, $is_bot, (string) time(), $ymd,
    ]);
} catch (Throwable $e) {
    error_log(SITE_ID . ' beacon: ' . $e->getMessage());
}
