#!/usr/bin/env python3
"""
{{SERVICE_NAME}} — gNode Service Bootstrap

Generated by: geodineum new service {{SERVICE_NAME}}

Connects to the gNode mesh via ValKey streams (XADD/XREADGROUP).

Bootstrap order:
  1. Read .geodineum/config.yaml for ValKey connection details
  2. Load credential from .geodineum/credentials/ symlink
  3. Connect to ValKey with ACL authentication
  4. Send/receive commands on the unified stream

Requires: pip install redis pyyaml

See: https://github.com/geodineum/gNode
"""

import json
import os
import re
import time
import uuid
from pathlib import Path

import redis


def load_config() -> dict:
    """Load configuration from .geodineum/config.yaml, then .env fallback."""
    config = {}

    # Try .geodineum/config.yaml first (preferred bootstrap)
    geodineum_dir = Path(__file__).parent.parent / ".geodineum"
    config_yaml = geodineum_dir / "config.yaml"

    if config_yaml.exists():
        content = config_yaml.read_text()

        # Simple YAML parsing (no pyyaml dependency required for bootstrap)
        m = re.search(r'^site_id:\s*"?([^"\n]+)"?', content, re.MULTILINE)
        if m:
            config["site_id"] = m.group(1).strip()

        m = re.search(r'^\s+host:\s*"?([^"\n]+)"?', content, re.MULTILINE)
        if m:
            config["valkey_host"] = m.group(1).strip()

        m = re.search(r'^\s+port:\s*(\d+)', content, re.MULTILINE)
        if m:
            config["valkey_port"] = int(m.group(1))

        m = re.search(r'^\s+user:\s*"?([^"\n]+)"?', content, re.MULTILINE)
        if m:
            config["valkey_user"] = m.group(1).strip()

        m = re.search(r'^\s+password_file:\s*"?([^"\n]+)"?', content, re.MULTILINE)
        if m:
            pass_file = Path(m.group(1).strip())
            if pass_file.exists():
                config["valkey_pass"] = pass_file.read_text().strip()

        m = re.search(r'^environment:\s*"?([^"\n]+)"?', content, re.MULTILINE)
        if m:
            config["environment"] = m.group(1).strip()

    # Fall back to .env for anything not found in .geodineum
    env_file = Path(__file__).parent.parent / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                os.environ.setdefault(key.strip(), value.strip())

    # Fill in missing values from environment
    config.setdefault("site_id", os.getenv("GNODE_SITE_ID", "{{SITE_ID}}"))
    config.setdefault("environment", os.getenv("GNODE_ENVIRONMENT", "{{SERVICE_ENV}}"))
    config.setdefault("valkey_host", os.getenv("VALKEY_HOST", "127.0.0.1"))
    config.setdefault("valkey_port", int(os.getenv("VALKEY_PORT", "47445")))

    # Fallback credential loading if not found via .geodineum
    if "valkey_pass" not in config:
        cred_dir = os.getenv("GEODINEUM_CREDENTIALS_DIR", "/etc/geodineum/credentials")
        pass_file = Path(cred_dir) / f"valkey_client_{config['site_id']}.password"
        if pass_file.exists():
            config["valkey_pass"] = pass_file.read_text().strip()
            config["valkey_user"] = f"gnode_client_{config['site_id']}"

    return config


def connect(config: dict) -> redis.Redis:
    """Connect to ValKey with ACL authentication."""
    kwargs = {
        "host": config["valkey_host"],
        "port": config["valkey_port"],
        "decode_responses": True,
    }
    if "valkey_user" in config:
        kwargs["username"] = config["valkey_user"]
        kwargs["password"] = config["valkey_pass"]

    return redis.Redis(**kwargs)


def gnode_command(
    client: redis.Redis,
    stream: str,
    cmd: str,
    params: dict | None = None,
    timeout_ms: int = 5000,
) -> dict | None:
    """Send a command to gNode and wait for the response."""
    cmd_id = f"cmd_{uuid.uuid4().hex[:12]}"

    # Capture current stream position BEFORE sending (so we don't miss the response)
    info = client.xinfo_stream(stream)
    last_id = info.get("last-generated-id", "0-0")

    # Send command
    client.xadd(stream, {
        "id": cmd_id,
        "cmd": cmd,
        "params": json.dumps(params or {}),
        "_cr": "1",
    })

    # Wait for response (read from position just before our command)
    deadline = time.time() + (timeout_ms / 1000)
    while time.time() < deadline:
        remaining = max(100, int((deadline - time.time()) * 1000))
        results = client.xread({stream: last_id}, count=10, block=min(remaining, 500))
        if results:
            for _, messages in results:
                for msg_id, fields in messages:
                    last_id = msg_id
                    if fields.get("id") == cmd_id and "status" in fields:
                        return fields

    return None


# =============================================================================
# Main
# =============================================================================

def main():
    config = load_config()
    client = connect(config)

    stream = f"{config['site_id']}:gnode:unified:{config['environment']}"

    # Ping gNode
    response = gnode_command(client, stream, "ping")
    print(f"gNode response: {response.get('status', 'timeout') if response else 'timeout'}")

    # Example: discover services with compute capability
    # services = gnode_command(client, stream, "geometric_discover", {
    #     "capabilities": {"compute": 0.8},
    #     "limit": 5,
    # })
    # print(f"Found services: {json.loads(services.get('result', '[]'))}")


if __name__ == "__main__":
    main()
