<?php
/**
 * {{SERVICE_NAME}} — Standalone gCore Application
 *
 * Generated by: geodineum new service {{SERVICE_NAME}} --gcore
 *
 * Boots the full gCore framework (ecosystem config, managers,
 * gNode-Client) through the canonical standalone entry point.
 * No WordPress required — gCore is CMS-agnostic.
 *
 * Credential resolution is automatic via gNode-Client:
 *   ValKey user gnode_client_{{SITE_ID}}, password from the
 *   centralized credential store or environment.
 *
 * @see gCore/gcore-standalone.php
 */

declare(strict_types=1);

$gcoreEntry = getenv('GCORE_PATH') ?: '{{GCORE_ENTRY}}';
if (!is_file($gcoreEntry)) {
    fwrite(STDERR, "gCore standalone entry not found: {$gcoreEntry}" . PHP_EOL);
    fwrite(STDERR, "Install gCore, or point GCORE_PATH at gcore-standalone.php" . PHP_EOL);
    exit(1);
}
require_once $gcoreEntry;

$gCore = gcore_init([
    'site_id'     => getenv('GNODE_SITE_ID') ?: '{{SITE_ID}}',
    'environment' => getenv('GNODE_ENVIRONMENT') ?: '{{SERVICE_ENV}}',
]);

// Framework services (see gCore docblocks for the full catalog):
//   $gCore->getService('CacheManager')   — ValKey-backed cache
//   $gCore->getService('gnode_client')   — gNode mesh client
//   $gCore->getService('SecurityManager')
//   $gCore->getService('ErrorManager')

// Application logic starts here.
