<?php
/**
 * {{SERVICE_NAME}} — gNode Service Bootstrap
 *
 * Generated by: geodineum new service {{SERVICE_NAME}}
 *
 * This file connects your service to the gNode mesh via ValKey streams.
 * Commands are sent via XADD and responses received via XREADGROUP.
 *
 * Bootstrap order:
 *   1. Read .geodineum/config.yaml for ValKey connection details
 *   2. Load credential from .geodineum/credentials/ symlink
 *   3. Connect to ValKey with ACL authentication
 *   4. Send/receive commands on the unified stream
 *
 * @see https://github.com/geodineum/gNode
 */

declare(strict_types=1);

// Load environment (fallback for non-.geodineum setups)
$dotenv = __DIR__ . '/../.env';
if (file_exists($dotenv)) {
    $lines = file($dotenv, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach ($lines as $line) {
        if (str_starts_with(trim($line), '#')) continue;
        if (str_contains($line, '=')) {
            putenv(trim($line));
        }
    }
}

// Load configuration from .geodineum/config.yaml (preferred) or environment
$config = [];
$geodineumDir = __DIR__ . '/../.geodineum';
$configYaml = $geodineumDir . '/config.yaml';

if (file_exists($configYaml)) {
    // Parse YAML bootstrap config (simple key extraction, no YAML extension needed)
    $yamlContent = file_get_contents($configYaml);

    // Extract site_id
    if (preg_match('/^site_id:\s*"?([^"\n]+)"?/m', $yamlContent, $m)) {
        $config['site_id'] = trim($m[1]);
    }
    // Extract valkey connection
    if (preg_match('/^\s+host:\s*"?([^"\n]+)"?/m', $yamlContent, $m)) {
        $config['valkey_host'] = trim($m[1]);
    }
    if (preg_match('/^\s+port:\s*(\d+)/m', $yamlContent, $m)) {
        $config['valkey_port'] = (int)$m[1];
    }
    if (preg_match('/^\s+user:\s*"?([^"\n]+)"?/m', $yamlContent, $m)) {
        $config['valkey_user'] = trim($m[1]);
    }
    if (preg_match('/^\s+password_file:\s*"?([^"\n]+)"?/m', $yamlContent, $m)) {
        $passFile = trim($m[1]);
        if (file_exists($passFile)) {
            $config['valkey_pass'] = trim(file_get_contents($passFile));
        }
    }
    // Extract environment
    if (preg_match('/^environment:\s*"?([^"\n]+)"?/m', $yamlContent, $m)) {
        $config['environment'] = trim($m[1]);
    }
}

// Fill in any missing values from environment
$config += [
    'site_id'     => getenv('GNODE_SITE_ID') ?: '{{SITE_ID}}',
    'environment' => getenv('GNODE_ENVIRONMENT') ?: '{{SERVICE_ENV}}',
    'valkey_host' => getenv('VALKEY_HOST') ?: '127.0.0.1',
    'valkey_port' => (int)(getenv('VALKEY_PORT') ?: 47445),
];

// Fallback credential loading if not found via .geodineum
if (!isset($config['valkey_pass'])) {
    $credDir = getenv('GEODINEUM_CREDENTIALS_DIR') ?: '/etc/geodineum/credentials';
    $passFile = "{$credDir}/valkey_client_{$config['site_id']}.password";
    if (file_exists($passFile)) {
        $config['valkey_pass'] = trim(file_get_contents($passFile));
        $config['valkey_user'] = "gnode_client_{$config['site_id']}";
    }
}

// Connect to ValKey
$redis = new Redis();
$redis->connect($config['valkey_host'], $config['valkey_port']);
if (isset($config['valkey_pass'])) {
    $redis->auth([$config['valkey_user'], $config['valkey_pass']]);
}

// Stream names
$unified = "{$config['site_id']}:gnode:unified:{$config['environment']}";
$group   = "service_{{SITE_ID}}";
$consumer = "{{SERVICE_NAME}}_" . getmypid();

// Ensure consumer group exists
try {
    $redis->xGroup('CREATE', $unified, $group, '0', true);
} catch (RedisException $e) {
    // Group already exists — OK
}

/**
 * Send a command to gNode and wait for the response.
 */
function gnode_command(Redis $redis, string $stream, string $cmd, array $params = [], int $timeoutMs = 5000): ?array
{
    $id = uniqid('cmd_', true);

    // Capture current stream position BEFORE sending (so we don't miss the response)
    $info = $redis->xInfoStream($stream);
    $lastId = $info['last-generated-id'] ?? '0-0';

    // Send command
    $redis->xAdd($stream, '*', [
        'id'     => $id,
        'cmd'    => $cmd,
        'params' => json_encode($params),
        '_cr'    => '1',
    ]);

    // Wait for response (read from position just before our command)
    $deadline = microtime(true) + ($timeoutMs / 1000);
    while (microtime(true) < $deadline) {
        $remaining = max(100, (int)(($deadline - microtime(true)) * 1000));
        $messages = $redis->xRead([$stream => $lastId], 10, min($remaining, 500));
        if ($messages) {
            foreach ($messages[$stream] ?? [] as $msgId => $fields) {
                $lastId = $msgId;
                if (($fields['id'] ?? '') === $id && isset($fields['status'])) {
                    return $fields;
                }
            }
        }
    }

    return null;
}

// =============================================================================
// Your service logic starts here
// =============================================================================

// Example: ping gNode
$response = gnode_command($redis, $unified, 'ping');
echo "gNode response: " . ($response['status'] ?? 'timeout') . "\n";

// Example: discover services with compute capability
// $services = gnode_command($redis, $unified, 'geometric_discover', [
//     'capabilities' => ['compute' => 0.8],
//     'limit' => 5,
// ]);
