# =============================================================================
# Geodineum Unified Site/Service Configuration
# =============================================================================
# Canonical source of truth. Cached in ValKey at {site_id}:config:site
# Changes via: geodineum env set, geodineum config set, or edit directly.
# After editing, run: geodineum config sync <site_id>
#
# Generated by: geodineum new {{SERVICE_TYPE}} {{SERVICE_NAME}}
# =============================================================================

version: "2.0.0"
site_id: "{{SITE_ID}}"

# --- Identity ---
identity:
  type: {{SERVICE_TYPE}}
  tier: {{SERVICE_TIER}}
  domain: "{{SERVICE_DOMAIN}}"
  display_name: "{{SERVICE_NAME}}"
  description: "{{SERVICE_DESCRIPTION}}"
  owner: ""

# --- Environment & Gating ---
environment:
  active: {{SERVICE_ENV}}
  viewkey: ""
  viewkey_expiry: 86400

# --- ValKey Connection ---
valkey:
  host: "127.0.0.1"
  port: 47445
  user: "gnode_client_{{SITE_ID}}"
  password_file: "/etc/geodineum/credentials/valkey_client_{{SITE_ID}}.password"

# --- gNode Topology Capabilities ---
capabilities:
  protocol: {{CAP_PROTOCOL}}
  native_format: {{CAP_FORMAT}}
  api_version: v1
  contract_stability: {{CAP_STABILITY}}
  clearance_required: {{CAP_CLEARANCE}}
  auth_method: {{CAP_AUTH}}
  data_sensitivity: {{CAP_SENSITIVITY}}
  service_scope: {{CAP_SCOPE}}
  domain_primary: {{CAP_DOMAIN}}
  domain_secondary: {{CAP_DOMAIN_SECONDARY}}
  specialization: {{CAP_SPECIALIZATION}}
  throughput_tier: {{CAP_THROUGHPUT}}
  latency_class: {{CAP_LATENCY}}
  reliability_tier: {{CAP_RELIABILITY}}
  pipeline_stage: {{CAP_PIPELINE_STAGE}}
  execution_priority: {{CAP_PRIORITY}}

# --- Service Metadata ---
metadata:
  language: {{SERVICE_LANG}}
  framework: gCore
  created_by: geodineum-cli

# --- Registration ---
registration:
  method: smart
  check_hash_before_register: true
  sync_to_valkey: true
  valkey_config_ttl: 86400

# --- Notifications (Geodineum-COMMS) ---
# Uncomment and configure to enable email/Telegram/SMS notifications.
# comms:
#   enabled: true
#   channels:
#     email:
#       enabled: true
#       config:
#         smtp_host: "127.0.0.1"
#         smtp_port: 25
#         smtp_user: ""
#         smtp_pass: ""
#         from_email: "noreply@example.com"
#         from_name: "Notifications"
#         use_tls: false
#       recipients:
#         - email: "admin@example.com"
#           types: ["all"]
#           min_priority: 3
#   routing_rules:
#     - type: contact
#       channels: [email]
#   retry:
#     max_attempts: 5
#     base_delay_secs: 30
