# gNode Service Configuration
# ============================
# Generated by: geodineum new service {{SERVICE_NAME}}
# Template: {{TEMPLATE_NAME}}
#
# The daemon discovers this file automatically via discovery-paths.conf.
# Edit capabilities to match your service's actual profile.
# Changes are detected within ~120s (or restart daemon for immediate effect).

services:
  - id: "{{SERVICE_ID}}"
    metadata:
      description: "{{SERVICE_DESCRIPTION}}"
      type: "service"
      tier: "{{SERVICE_TIER}}"
      language: "{{SERVICE_LANG}}"
      created_by: "geodineum-cli"
    capabilities:
      # Layer 1: Interface Identity
      - name: "protocol"
        value: "{{CAP_PROTOCOL}}"
      - name: "native_format"
        value: "{{CAP_FORMAT}}"
      - name: "api_version"
        value: "v1"
      - name: "contract_stability"
        value: "{{CAP_STABILITY}}"

      # Layer 2: Access Control
      - name: "clearance_required"
        value: "{{CAP_CLEARANCE}}"
      - name: "auth_method"
        value: "{{CAP_AUTH}}"
      - name: "data_sensitivity"
        value: "{{CAP_SENSITIVITY}}"

      # Layer 3: Service Scope
      - name: "service_scope"
        value: "{{CAP_SCOPE}}"

      # Layer 4: Functional Domain
      - name: "domain_primary"
        value: "{{CAP_DOMAIN}}"
      - name: "domain_secondary"
        value: "{{CAP_DOMAIN_SECONDARY}}"
      - name: "specialization"
        value: "{{CAP_SPECIALIZATION}}"

      # Layer 5: Performance Profile
      - name: "throughput_tier"
        value: "{{CAP_THROUGHPUT}}"
      - name: "latency_class"
        value: "{{CAP_LATENCY}}"
      - name: "reliability_tier"
        value: "{{CAP_RELIABILITY}}"

      # Layer 6: Workflow Context
      - name: "pipeline_stage"
        value: "{{CAP_PIPELINE_STAGE}}"
      - name: "execution_priority"
        value: "{{CAP_PRIORITY}}"

      # Layer 8: Classification
      - name: "service_tier"
        value: "{{SERVICE_TIER}}"
      - name: "environment"
        value: "{{SERVICE_ENV}}"
