# Geodineum onboarding manifest — ONE schema (profile + environment +
# consumes/produces drive registration and the composed ValKey ACL).
# Generated by: geodineum new service {{SERVICE_NAME}}
# Template: {{TEMPLATE_NAME}}
# Contract: CONTRACTS/SERVICE_ONBOARDING.md

profile: {{PROFILE}}
environment: {{SERVICE_ENV}}

services:
  - id: "{{SERVICE_ID}}"
    metadata:
      description: "{{SERVICE_DESCRIPTION}}"
      type: "service"
      tier: "{{SERVICE_TIER}}"
      language: "{{SERVICE_LANG}}"
      created_by: "geodineum-cli"

# Declared grants, composed + policy-validated at onboarding (own namespace
# + well-known shared trees only — anything foreign is refused; request
# cross-service access via the grant loop instead).
consumes: []
produces:
  - "{{{SERVICE_ID}}}:gnode:comms:*"
