# ==============================================================================
# Site-Specific Configuration
# ==============================================================================
# Generated by: geodineum new site {{DOMAIN}}
#
# Location: /etc/geodineum/sites/{{SITE_ID}}/site.env
# Permissions: gnode:www-data 640 (PHP readable via www-data group)
# ==============================================================================

# ==============================================================================
# §1 SITE IDENTITY
# ==============================================================================
GNODE_SITE_ID="{{SITE_ID}}"
GNODE_ENVIRONMENT="{{SERVICE_ENV}}"

# ==============================================================================
# §2 CREDENTIAL REFERENCE
# ==============================================================================
# Auto-resolved by CredentialResolver — only override if non-standard.

# VALKEY_PASSWORD_FILE="/etc/geodineum/credentials/valkey_client_{{SITE_ID}}.password"
# VALKEY_USER="gnode_client_{{SITE_ID}}"

# ==============================================================================
# §3 SITE-SPECIFIC OVERRIDES (Optional)
# ==============================================================================
# Override shared settings from /etc/geodineum/bootstrap.env if needed.

# GNODE_STREAM_PREFIX="gnode"
# GNODE_DEFAULT_ENVIRONMENT="staging"

# ==============================================================================
# §4 SITE CACHE SETTINGS (Optional)
# ==============================================================================
# GCORE_CACHE_TTL="1800"
