#!/bin/bash
# =============================================================================
# join-constellation.sh — add this host to an existing Geodineum constellation
# =============================================================================
# Worker-side helper. Brings up a WireGuard tunnel to the constellation master,
# then runs a headless (or full) install that connects to the master's ValKey.
#
# The master is the source of truth for membership: this script PAUSES so you
# can run `geodineum constellation add-peer` there. A node cannot join the VPN
# until the master has registered its public key — provisioning is top-down.
#
# Prereqsuisite (on the master, once):
#   sudo geodineum constellation init
#   geodineum constellation status        # note the master's public key + endpoint
#
# Usage (on the new node, as root):
#   sudo ./join-constellation.sh \
#       --master-pubkey   "<master_wg_public_key>" \
#       --master-endpoint "<master_public_ip>:51820" \
#       --worker-vpn-ip   10.66.0.2 \
#       --worker-public   "<this_node_public_ip>"          # for the add-peer endpoint
#
# Options:
#   --tier <headless|full>   Deploy tier (default: headless)
#   --master-vpn-ip <ip>     Master's VPN IP (default: 10.66.0.1)
#   --wg-port <port>         WireGuard UDP port (default: 51820)
#   --name <name>            Peer name shown on the master (default: hostname)
#   --yes                    Don't pause for the add-peer step (assume done)
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WG_IFACE="wg-geodineum"
WG_CONF="/etc/wireguard/${WG_IFACE}.conf"
WG_KEY="/etc/wireguard/${WG_IFACE}.key"

MASTER_PUBKEY=""
MASTER_ENDPOINT=""
WORKER_VPN_IP=""
WORKER_PUBLIC=""
MASTER_VPN_IP="10.66.0.1"
WG_PORT="51820"
TIER="headless"
PEER_NAME="$(hostname -s 2>/dev/null || echo node)"
ASSUME_PEERED="false"

die() { echo "ERROR: $*" >&2; exit 1; }
info() { echo "[*] $*"; }
ok()   { echo "[OK] $*"; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --master-pubkey)   MASTER_PUBKEY="$2"; shift 2 ;;
        --master-endpoint) MASTER_ENDPOINT="$2"; shift 2 ;;
        --worker-vpn-ip)   WORKER_VPN_IP="$2"; shift 2 ;;
        --worker-public)   WORKER_PUBLIC="$2"; shift 2 ;;
        --master-vpn-ip)   MASTER_VPN_IP="$2"; shift 2 ;;
        --wg-port)         WG_PORT="$2"; shift 2 ;;
        --tier)            TIER="$2"; shift 2 ;;
        --name)            PEER_NAME="$2"; shift 2 ;;
        --yes)             ASSUME_PEERED="true"; shift ;;
        -h|--help)         sed -n '2,40p' "$0"; exit 0 ;;
        *)                 die "Unknown arg: $1" ;;
    esac
done

[[ "$EUID" -eq 0 ]] || die "must run as root"
[[ -n "$MASTER_PUBKEY" ]]   || die "--master-pubkey required (from: geodineum constellation status, on the master)"
[[ -n "$MASTER_ENDPOINT" ]] || die "--master-endpoint required (master_public_ip:${WG_PORT})"
[[ -n "$WORKER_VPN_IP" ]]   || die "--worker-vpn-ip required (e.g. 10.66.0.2 — must be free in the constellation)"
[[ "$TIER" == "headless" || "$TIER" == "full" ]] || die "--tier must be headless or full (replica is experimental; use the installer directly)"

# ── 1. WireGuard tooling ────────────────────────────────────────────────────
if ! command -v wg >/dev/null 2>&1; then
    info "Installing wireguard-tools..."
    apt-get update -qq && apt-get install -y wireguard-tools >/dev/null
fi

# ── 2. Worker keypair (idempotent) ──────────────────────────────────────────
if [[ ! -s "$WG_KEY" ]]; then
    info "Generating WireGuard keypair..."
    umask 077; wg genkey > "$WG_KEY"
fi
WORKER_PRIVKEY="$(cat "$WG_KEY")"
WORKER_PUBKEY="$(echo "$WORKER_PRIVKEY" | wg pubkey)"

# ── 3. WireGuard config ─────────────────────────────────────────────────────
info "Writing ${WG_CONF}..."
umask 077
cat > "$WG_CONF" <<EOF
# Geodineum constellation node — generated by join-constellation.sh
[Interface]
Address = ${WORKER_VPN_IP}/24
ListenPort = ${WG_PORT}
PrivateKey = ${WORKER_PRIVKEY}

[Peer]
# Constellation master
PublicKey = ${MASTER_PUBKEY}
Endpoint = ${MASTER_ENDPOINT}
AllowedIPs = 10.66.0.0/24
PersistentKeepalive = 25
EOF
chmod 600 "$WG_CONF"

# ── 4. Top-down registration on the master ──────────────────────────────────
echo ""
echo "  ┌─ Run this ON THE MASTER to admit this node: ─────────────────────────"
echo "  │  sudo geodineum constellation add-peer ${PEER_NAME} \\"
echo "  │      \"${WORKER_PUBKEY}\" \\"
echo "  │      \"${WORKER_PUBLIC:-<this_node_public_ip>}:${WG_PORT}\""
echo "  └──────────────────────────────────────────────────────────────────────"
echo ""
if [[ "$ASSUME_PEERED" != "true" ]]; then
    read -r -p "  Press ENTER once the master has added this peer (Ctrl-C to abort)... " _
fi

# ── 5. Bring up the tunnel ──────────────────────────────────────────────────
info "Starting WireGuard..."
systemctl enable "wg-quick@${WG_IFACE}" >/dev/null 2>&1 || true
systemctl restart "wg-quick@${WG_IFACE}"

# ── 6. Verify VPN reachability ──────────────────────────────────────────────
info "Pinging master at ${MASTER_VPN_IP} over the VPN..."
reachable="false"
for _ in 1 2 3 4 5; do
    if ping -c1 -W2 "$MASTER_VPN_IP" >/dev/null 2>&1; then reachable="true"; break; fi
    sleep 1
done
[[ "$reachable" == "true" ]] || die "cannot reach master at ${MASTER_VPN_IP} — check the add-peer step, firewall (UDP ${WG_PORT}), and the endpoint"
ok "VPN up — master reachable at ${MASTER_VPN_IP}"

# ── 7. Headless / full install ──────────────────────────────────────────────
INSTALL_SH="${SCRIPT_DIR}/../install.sh"
[[ -x "$INSTALL_SH" ]] || INSTALL_SH="$(command -v geodineum-install || true)"
[[ -n "$INSTALL_SH" && -f "$INSTALL_SH" ]] || die "install.sh not found next to this script"

info "Running install: --deploy-tier ${TIER} --master-ip ${MASTER_VPN_IP}"
bash "$INSTALL_SH" --deploy-tier "$TIER" --master-ip "$MASTER_VPN_IP" --yes

echo ""
ok "Node joined the constellation (${TIER})."
echo ""
echo "  Next:"
echo "   1. Copy the master's daemon password to this node so it can authenticate:"
echo "        # on master:  sudo cat /etc/geodineum/credentials/valkey_daemon.password"
echo "        # on node:    sudo install -o gnode -g geodineum-creds -m 640 /dev/stdin \\"
echo "                        /etc/geodineum/credentials/valkey_daemon.password   # paste, Ctrl-D"
echo "   2. Smoke-test the connection:"
echo "        sudo ${SCRIPT_DIR}/smoketest-node.sh --master-ip ${MASTER_VPN_IP}"
