<?php
/**
 * {{DOMAIN}} — front controller ({{SITE_ID}})
 *
 * Generated by: geodineum service new {{DOMAIN}} --type webapp-gcore
 *
 * The only PHP the web server can reach. Application code lives in ../src,
 * outside the docroot; bootstrap.php boots gCore through the canonical
 * standalone entry point and leaves $gCore in scope here.
 */

declare(strict_types=1);

require_once dirname(__DIR__) . '/src/bootstrap.php';

// Route from here. Framework services are live:
//   $gCore->getService('SecurityManager')
//   $gCore->getService('CacheManager')
//   $gCore->getService('gnode_client')
header('Content-Type: text/plain; charset=utf-8');
echo "{{DOMAIN}}: gCore is bootstrapped. Replace this front controller.\n";
